[tool.poetry]
name = "test"
version = "0.1.0"
description = "render_test"
authors = ["dperry713 <dperry713@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "=\"^7.0\""


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
